name: Self Check on Branch

on:
  push:
    branches:
      - main  # or specify your branch name
      - testdevops

jobs:
  self-check:
    runs-on: self-hosted   # Use your self-hosted runner label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run self check script
        run: |
          echo "Performing self check..."
