name: Self Check on Branch

on:
  push:
    branches:
      - main  # or specify your branch name
      - testdevops

jobs:
  self-check:
    runs-on: self-hosted   # Use your self-hosted runner label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run self check script
	env:
          REPO_URL: https://github.com/djkaz/tesdevops.git
          BRANCH_NAME: main	
        run: |
	  chmod +x ./check-and-deploy.sh
          ./check-and-deploy.sh
          #echo "Performing self check..."
	  #echo "Running checks for PR ${{ github.event.number }}"
