name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JOB_NAME: 'MyRemoteTriggerPipeline'
        run: |
          curl -X POST "$JENKINS_URL/job/$JOB_NAME/build" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"
